name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - run: cd p && ./gradlew assembleDebug

    - uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: p/app/build/outputs/apk/debug/app-debug.apk

# TODO
